services:
  arob3:
    image: aroblab3
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: aroblab3
    environment:
      DISPLAY: $DISPLAY
      ROS_LOCALHOST_ONLY: 1
    privileged: true
    volumes:
      # X11
      - ~/.Xauthority:/root/.Xauthority
      # 
      - /dev/:/dev
      # Code
      - ./p00_arob_lab3_drones:/root/catkin_ws/src/p00_arob_lab3_drones
    network_mode: "host"
    command: tail -f /dev/null
